export const FETCH_KOLOTI_CACHE_REQUEST = 'FETCH_KOLOTI_CACHE_REQUEST';
export const FETCH_KOLOTI_CACHE_SUCCESS = 'FETCH_KOLOTI_CACHE_SUCCESS';
export const FETCH_KOLOTI_CACHE_FAILURE = 'FETCH_KOLOTI_CACHE_FAILURE';

export const DELETE_KOLOTI_CACHE_REQUEST = 'DELETE_KOLOTI_CACHE_REQUEST';
export const DELETE_KOLOTI_CACHE_SUCCESS = 'DELETE_KOLOTI_CACHE_SUCCESS';
export const DELETE_KOLOTI_CACHE_FAILURE = 'DELETE_KOLOTI_CACHE_FAILURE';

export const UPDATE_KOLOTI_CACHE_ANSWER_REQUEST = 'UPDATE_KOLOTI_CACHE_ANSWER_REQUEST';
export const UPDATE_KOLOTI_CACHE_ANSWER_SUCCESS = 'UPDATE_KOLOTI_CACHE_ANSWER_SUCCESS';
export const UPDATE_KOLOTI_CACHE_ANSWER_FAILURE = 'UPDATE_KOLOTI_CACHE_ANSWER_FAILURE';
