export const REGISTER_REQUEST = 'auth/REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'auth/REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'auth/REGISTER_FAILURE';

export const VERIFY_EMAIL_REQUEST = 'auth/VERIFY_EMAIL_REQUEST';
export const VERIFY_EMAIL_SUCCESS = 'auth/VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILURE = 'auth/VERIFY_EMAIL_FAILURE';

export const RESEND_VERIFICATION_REQUEST = 'auth/RESEND_VERIFICATION_REQUEST';
export const RESEND_VERIFICATION_SUCCESS = 'auth/RESEND_VERIFICATION_SUCCESS';
export const RESEND_VERIFICATION_FAILURE = 'auth/RESEND_VERIFICATION_FAILURE';

export const RESET_AUTH_STATE = 'auth/RESET_AUTH_STATE';
