export const FETCH_CRYPTO_CONFIG_REQUEST = 'FETCH_CRYPTO_CONFIG_REQUEST';
export const FETCH_CRYPTO_CONFIG_SUCCESS = 'FETCH_CRYPTO_CONFIG_SUCCESS';
export const FETCH_CRYPTO_CONFIG_FAILURE = 'FETCH_CRYPTO_CONFIG_FAILURE';

export const FETCH_CRYPTO_PRICE_REQUEST = 'FETCH_CRYPTO_PRICE_REQUEST';
export const FETCH_CRYPTO_PRICE_SUCCESS = 'FETCH_CRYPTO_PRICE_SUCCESS';
export const FETCH_CRYPTO_PRICE_FAILURE = 'FETCH_CRYPTO_PRICE_FAILURE';

export const RECORD_DEPOSIT_REQUEST = 'RECORD_DEPOSIT_REQUEST';
export const RECORD_DEPOSIT_SUCCESS = 'RECORD_DEPOSIT_SUCCESS';
export const RECORD_DEPOSIT_FAILURE = 'RECORD_DEPOSIT_FAILURE';
